services:
    postgres:
        image: 'pgvector/pgvector:pg17'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: my-local-db
        ports:
            - '5353:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
